name: Benchmark

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      run_full_benchmark:
        description: 'Run full benchmark suite'
        required: false
        default: 'false'
        type: boolean

jobs:
  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'benchmark')
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libexif-dev libheif-dev exiftool

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Run basic benchmark
      run: |
        if [ -f "utils/benchmark.py" ]; then
          python -m utils.benchmark --quick
        else
          echo "No benchmark script found, skipping"
        fi

    - name: Run full benchmark
      if: github.event.inputs.run_full_benchmark == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        if [ -f "utils/benchmark.py" ]; then
          python -m utils.benchmark --full
        else
          echo "No benchmark script found, skipping"
        fi

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: |
          benchmark/reports/
          benchmark/results/