name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday

jobs:
  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    continue-on-error: false  # Only fail on critical/high issues

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Only 3.11 and 3.12 are supported
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Run Safety (dependency vulnerabilities)
      continue-on-error: true  # Do not fail build on low/medium issues
      run: |
        safety check --full-report --output safety-report.json --json || true
        # Fail only if critical/high vulnerabilities are found
        python3 -c "import json; r=json.load(open('safety-report.json')); import sys; sys.exit(any(v.get('severity','').lower() in ['high','critical'] for v in r.get('vulnerabilities', [])))"
    
    - name: Run Bandit (code security)
      continue-on-error: true  # Do not fail build on Bandit warnings
      run: |
        bandit -r . -f json -o bandit-report.json --skip B101,B104,B107,B108,B311,B404,B601,B602,B603,B607 || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json